### ISSUE TITLE
Create find screen for pre-order catalog

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#118]
## What is the motivation for adding/enhancing this feature?
Merchandisers require the ability to audit whether a product is accepting pre-order/backorder, and should be able to search for a specific product directly from the Catalog page in order to view its current status.

## What are the acceptance criteria?
1. The search functionality should allow merchandisers to search for products by their SKU.
2. The product page should display the current pre-order/backorder status of the product, including any relevant details such as `from` and `through` dates.

## Can you complete this feature request by yourself?

- [ ] YES
- NO

## Additional information
Link to figma file: https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?node-id=13416%3A0&t=DXQd9NgF4cyTehn7-1

Image for reference: 
<img width="1440" alt="Find Product page" src="https://user-images.githubusercontent.com/119936391/233999614-03666c48-701a-45e9-948b-bc8d985b4546.png">

**Comment by k2maan** [comment]
Implemented searching and filtering for preorders and backorders in #119 . Will create a new PR for the jobs section.
