### ISSUE TITLE
Create detail screen for pre-order catalog

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#125]
## What is the motivation for adding/enhancing this feature?
The current product catalog auditing process for pre-order products is proving to be time-consuming and inefficient. Users are required to switch between multiple views, leading to difficulties in reconciling data accurately. To address this issue, we propose enhancing the auditing process by consolidating all necessary views into a single screen.

## What are the acceptance criteria?
1. Must have pre-sell eligibility view.
2. Must have product's current product category view.
3. Must have Shopify listing status view.
4. Must have pre-order related jobs view.

## Can you complete this feature request by yourself?

- [ ] YES
- NO

## Additional information
Link to figma file: 
(https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=25387%3A127781&t=xx7jmyPJJrwLVDUD-1)

**Comment by adityasharma7** [comment]
<img width="226" alt="image" src="https://github.com/hotwax/preorder/assets/15027245/cbc94433-4e49-4831-ac20-0ae7d56f2aad">

**Comment by adityasharma7** [comment]
<img width="226" alt="image" src="https://github.com/hotwax/preorder/assets/15027245/99a25bbc-8e17-42b4-8ca6-16a374d567d6">

**Comment by adityasharma7** [comment]
<img width="210" alt="image" src="https://github.com/hotwax/preorder/assets/15027245/166f3ffc-827b-4c66-bebb-e3c2666bd7a9">

**Comment by adityasharma7** [comment]
<img width="210" alt="image" src="https://github.com/hotwax/preorder/assets/15027245/18939b03-6bef-47a4-a6cc-2ca90bc9dfc6">

**Comment by dt2patel** [comment]
Implemented in #137, closing task
