### ISSUE TITLE
Inconsistent Header in Purchase Order Card

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#147]
## Current behavior
The Purchase Order card displays the header "Last active purchase order" for an active purchase order.

## Expected behavior
The Purchase Order card header should provide consistent information that aligns with the displayed data.

## Steps to reproduce the issue
1. Go to the details page using the provided link: [Catalog Product Details](https://preorder-dev.hotwax.io/catalog-product-details/10000/10012).
2. Observe the data presented in both the Purchase Order card

Upon following these steps, you will notice that the header in the Purchase Order card does not accurately represent the status of the active purchase order.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
<img width="1673" alt="Screenshot 2023-06-27 at 11 21 41 AM" src="https://github.com/hotwax/preorder/assets/119936391/29f7bba8-f7a8-4a37-98fd-f228f777962e">

**Comment by dt2patel** [comment]
If a product is in a category, the PO is active because if an order comes in for this product, it will be sent for pre-order
