### ISSUE TITLE
Recently removed product from the presell category do not show their last active PO information

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#168]
## Current behavior
Products which are recently removed from the presell (pre-order/backorder)category do not show their last active PO information in the Purchase Order card.

## Expected behavior
If products are recently removed from the presell category, they must show their last active PO information. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
<img width="1680" alt="Screenshot 2023-06-30 at 6 55 27 PM" src="https://github.com/hotwax/preorder/assets/119936391/6097766e-04b6-4736-9c15-0d2038654b46">

**Comment by dt2patel** [comment]
if a product is removed from pre-order. we will not show last active anymore. this is a design choice
