### ISSUE TITLE
Implement list messages when job is in running state

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#212]
## What is the motivation for adding/enhancing this feature?
The motivation for adding/enhancing this feature is to improve the user experience when a job takes longer than expected. For example; Currently, users encounter the message `Adding to the <category> in 0 minutes`

## What are the acceptance criteria?
1. Implement a list of messages that dynamically update as the job progresses.
2. Messages should include relevant information such as job status and any notable milestones.
- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Will add UI here

**Comment by dt2patel** [comment]
We'll pick this when notifications are enabled for job status so that we can update UI in real time.

**Comment by Dhiraj1405** [comment]
Not required for now. Hence, closing
