### ISSUE TITLE
Product Summary and Shop Listing Status Not Loading

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#231]
## Current behavior
Product summaries and shop listing statuses are either not loading on the Pre-order Audit page. 

## Expected behavior
When users visit the Pre-order Audit page, they should be able to view product summaries and shop listing statuses without any delays or errors.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
Issue rectified on code level, need further communication from the BA team to start implementation.
