### ISSUE TITLE
Change Variable Naming Convention to CamelCase on the Orders Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#244]
## Current behavior
On the Orders page, the variable names are currently not following the camelCase convention, which is the standard naming convention in our codebase. To maintain consistency and improve readability, it is necessary to update the variable names on this page to camelCase.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by RishabhDhawad** [comment]
I am interested in contributing to this issue,
can you please assign it to me?

**Comment by k2maan** [comment]
Sure @RishabhDhawad go ahead
