### ISSUE TITLE
Remove Redundant `the` from Background Jobs Model Empty State

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#246]
## Current behavior
In the background jobs model empty state, there is a redundant occurrence of the word "the." This redundancy affects the clarity and professionalism of the user interface.

## Expected behavior
The redundant "the" should be removed from the background jobs model empty state to improve the overall consistency and readability of the interface.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
<img width="1439" alt="Screenshot 2023-10-11 at 2 35 21 PM" src="https://github.com/hotwax/preorder/assets/119936391/1f54f2d2-c52d-404c-ae7b-3a45a6166517">

**Comment by KanishkaPatidar** [comment]
can you assign this issue to me

**Comment by Dhiraj1405** [comment]
> can you assign this issue to me

Sure, go ahead

**Comment by Jitisha-khede** [comment]
I have fixed this issue and generated a pull request with name "preorder/#246" please have a look on it .
