### ISSUE TITLE
Implement Spinner During Product Scrolling on Pre-order Audit Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/preorder#264]
## What is the motivation for adding/enhancing this feature?
The current user experience on the Pre-order Audit page lacks a visual indicator during product scrolling, leading to potential confusion for users. This ticket aims to enhance the user interface by implementing a spinner to provide visual feedback when products are being loaded during scrolling.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.18.1.
