### ISSUE TITLE
Implement feature to update password when receive requirePasswordChange with login API

### ISSUE THREAD

**Issue by disha1202** [hotwax/preorder#84]
## What is the motivation for adding/enhancing this feature?

The feature is specifically useful when the default password is set for the new/old user and the user needs to be obliged to change the password on login.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by k2maan** [comment]
Will be done in #105
