### ISSUE TITLE
Update Settings page with updated UI

### ISSUE THREAD

**Issue by shashwatbangar** [hotwax/preorder#94]
Reference - https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=23579%3A83419&t=EwnGrKo71tXMohaa-0

**Comment by adityasharma7** [comment]
@shashwatbangar 
I think there is a UI issue, heading are too close to menu
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/15027245/208095996-66b18c02-f90b-4ab6-bdfd-f1b4bbeea575.png">
